//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the FluentMappingGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace WeaponsFactory.DataAccess
{
    using System.Collections.Generic;
    using Telerik.OpenAccess.Metadata;
    using Telerik.OpenAccess.Metadata.Fluent;

    public partial class WeaponsFactoryModelMetadataSource : FluentMetadataSource
	{
		protected override IList<MappingConfiguration> PrepareMapping()
		{
            List<MappingConfiguration> configurations = new List<MappingConfiguration>();

            var reportsMapping = new MappingConfiguration<ProductReport>();
            reportsMapping.MapType(sale => new
            {
                WeaponId = sale.WeaponId,
                WeaponName = sale.WeaponName,
                VendorName = sale.ManufacturerName,
                Quantity = sale.Quantity,
                Income = sale.Income
            }).ToTable("Reports");
            reportsMapping.HasProperty(c => c.WeaponId).IsIdentity(KeyGenerator.HighLow);

            configurations.Add(reportsMapping);

            return configurations;
		}
		
		protected override void SetContainerSettings(MetadataContainer container)
		{
			container.Name = "WeaponsFactoryModel";
			container.DefaultNamespace = "WeaponsFactory.DataAccess";
			container.NameGenerator.SourceStrategy = Telerik.OpenAccess.Metadata.NamingSourceStrategy.Property;
			container.NameGenerator.RemoveCamelCase = false;
		}
	}
}
