-- MySQL Script generated by MySQL Workbench
-- 08/24/14 14:38:24
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema MySQLUniversitiesDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `MySQLUniversitiesDB` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `MySQLUniversitiesDB` ;

-- -----------------------------------------------------
-- Table `MySQLUniversitiesDB`.`Faculties`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MySQLUniversitiesDB`.`Faculties` (
  `FacultyID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`FacultyID`),
  UNIQUE INDEX `FacultyID_UNIQUE` (`FacultyID` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MySQLUniversitiesDB`.`Students`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MySQLUniversitiesDB`.`Students` (
  `StudentID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  `FacultyID` INT NOT NULL,
  PRIMARY KEY (`StudentID`, `FacultyID`),
  UNIQUE INDEX `StudentID_UNIQUE` (`StudentID` ASC),
  INDEX `fk_Students_Faculties1_idx` (`FacultyID` ASC),
  CONSTRAINT `fk_Students_Faculties1`
    FOREIGN KEY (`FacultyID`)
    REFERENCES `MySQLUniversitiesDB`.`Faculties` (`FacultyID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MySQLUniversitiesDB`.`Departments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MySQLUniversitiesDB`.`Departments` (
  `DepartmentID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  `FacultyID` INT NOT NULL,
  PRIMARY KEY (`DepartmentID`, `FacultyID`),
  UNIQUE INDEX `DepartmentID_UNIQUE` (`DepartmentID` ASC),
  INDEX `fk_Departments_Faculties1_idx` (`FacultyID` ASC),
  CONSTRAINT `fk_Departments_Faculties1`
    FOREIGN KEY (`FacultyID`)
    REFERENCES `MySQLUniversitiesDB`.`Faculties` (`FacultyID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MySQLUniversitiesDB`.`Professors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MySQLUniversitiesDB`.`Professors` (
  `ProfessorID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  `DepartmentID` INT NOT NULL,
  UNIQUE INDEX `ProfessorID_UNIQUE` (`ProfessorID` ASC),
  PRIMARY KEY (`ProfessorID`, `DepartmentID`),
  INDEX `fk_Professors_Departments1_idx` (`DepartmentID` ASC),
  CONSTRAINT `fk_Professors_Departments1`
    FOREIGN KEY (`DepartmentID`)
    REFERENCES `MySQLUniversitiesDB`.`Departments` (`DepartmentID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MySQLUniversitiesDB`.`Courses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MySQLUniversitiesDB`.`Courses` (
  `CourseID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  `DepartmentID` INT NOT NULL,
  `ProfessorID` INT NOT NULL,
  PRIMARY KEY (`CourseID`, `DepartmentID`, `ProfessorID`),
  UNIQUE INDEX `CourseID_UNIQUE` (`CourseID` ASC),
  INDEX `fk_Courses_Departments1_idx` (`DepartmentID` ASC),
  INDEX `fk_Courses_Professors1_idx` (`ProfessorID` ASC),
  CONSTRAINT `fk_Courses_Departments1`
    FOREIGN KEY (`DepartmentID`)
    REFERENCES `MySQLUniversitiesDB`.`Departments` (`DepartmentID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Courses_Professors1`
    FOREIGN KEY (`ProfessorID`)
    REFERENCES `MySQLUniversitiesDB`.`Professors` (`ProfessorID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MySQLUniversitiesDB`.`Students_Courses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MySQLUniversitiesDB`.`Students_Courses` (
  `StudentID` INT NOT NULL,
  `CourseID` INT NOT NULL,
  PRIMARY KEY (`StudentID`, `CourseID`),
  INDEX `fk_Students_Courses_Courses1_idx` (`CourseID` ASC),
  CONSTRAINT `fk_Students_Courses_Students1`
    FOREIGN KEY (`StudentID`)
    REFERENCES `MySQLUniversitiesDB`.`Students` (`StudentID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Students_Courses_Courses1`
    FOREIGN KEY (`CourseID`)
    REFERENCES `MySQLUniversitiesDB`.`Courses` (`CourseID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MySQLUniversitiesDB`.`Titles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MySQLUniversitiesDB`.`Titles` (
  `TitleID` INT NOT NULL AUTO_INCREMENT,
  `Title` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`TitleID`),
  UNIQUE INDEX `TitleID_UNIQUE` (`TitleID` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MySQLUniversitiesDB`.`Professors_Titles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MySQLUniversitiesDB`.`Professors_Titles` (
  `ProfessorID` INT NOT NULL,
  `TitleID` INT NOT NULL,
  PRIMARY KEY (`ProfessorID`, `TitleID`),
  INDEX `fk_Professors_Titles_Titles1_idx` (`TitleID` ASC),
  CONSTRAINT `fk_Professors_Titles_Professors1`
    FOREIGN KEY (`ProfessorID`)
    REFERENCES `MySQLUniversitiesDB`.`Professors` (`ProfessorID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Professors_Titles_Titles1`
    FOREIGN KEY (`TitleID`)
    REFERENCES `MySQLUniversitiesDB`.`Titles` (`TitleID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
